#!/bin/bash
#--------------------------- Description ---------------------------------#

# This script tries to generate data for supplementary gene ontology gene-set
# table from PleioFDR/FUMA/ConsensusPDB analysis WITHOUT WARRANTY.

# Yunhan Chu (yunhanch@gmail.com), Guy F. L. Hindley

# (c) 2020-2022 NORMENT, UiO

#-------------------------------------------------------------------------#
if [ $# -lt 3 ]; then
  echo "Usage:     sh fdr_cpdb_pathway_table.sh fdr_fuma_gene_table cpdb_ora_file outfile"
  echo "Arguments: fdr_fuma_gene_table - TRAIT1_vs_TRAIT2_genes.txt file generated by script fdr_fuma_gene_table.sh"
  echo "           cpdb_ora_file - file that contains cpdb gene-set info"
  echo "           outfile - output file"
  echo "Example:   sh fdr_cpdb_pathway_table.sh MD_vs_CRP_genes.txt ORA_MD_CRP.txt MD_vs_CRP_path.txt"
  exit 0
fi
#-------------------------------------------------------------------------#

fdr_fuma_gene_table=$1
cpdb_ora_file=$2
outfile=$3

echo 'source	external_id	pathway	p-value	q-value	effective_size	overlap_size	genes_into_overlap	credible' > $outfile
awk '$NF=="Yes" {print $1}' $fdr_fuma_gene_table | sort | uniq | sort > $fdr_fuma_gene_table.tmp
rm -f $outfile.tmp2
tail -n +2 $cpdb_ora_file | cut -f6 | while read id; do
    echo $id | sed 's/; /\n/g' | sort | uniq | sort > $outfile.tmp
    n_overlap=`cat $outfile.tmp | wc -l`
    if [ `join $fdr_fuma_gene_table.tmp $outfile.tmp | wc -l` -gt 0 ]; then
        echo $n_overlap"	"$id"	Yes" >> $outfile.tmp2
    else
        echo $n_overlap"	"$id"	No" >> $outfile.tmp2
    fi
done
tail -n +2 $cpdb_ora_file | cut -f1-5,9 > $cpdb_ora_file.tmp
paste $cpdb_ora_file.tmp $outfile.tmp2 > $outfile.tmp
sort -t'	' -k4,4 -k3,3 $outfile.tmp | grep 'Yes$' > $outfile.tmp2
sort -t'	' -k4,4 -k3,3 $outfile.tmp | grep 'No$' >> $outfile.tmp2
awk -F '\t' '{print $4,$5,$3,$1,$2,$6,$7,$8,$9}' OFS='\t' $outfile.tmp2 | sed 's/&gamma;/gamma/g' >> $outfile

n_source=`tail -n +2 $outfile | cut -f1 | sort | uniq | wc -l`
n_path=`tail -n +2 $outfile | wc -l`
n_cred=`cut -f9 $outfile | grep Yes | wc -l`
sum_effect_genes=`tail -n +2 $outfile | awk -F '\t' '{sum += $6} END {print sum}'`
sum_overlap=`tail -n +2 $outfile | awk -F '\t' '{sum += $7} END {print sum}'`
echo $n_source $n_path $sum_effect_genes $sum_overlap $n_cred | awk '{print $1"\t"$2"\t\t\t\t"$3"\t"$4"\t\t"$5}' >> $outfile

rm -f $fdr_fuma_gene_table.tmp $cpdb_ora_file.tmp $outfile.tmp $outfile.tmp2
