#!/bin/bash
#--------------------------- Description ---------------------------------#

# This script tries to generate data for supplementary gene ontology gene-set
# table from PleioFDR/FUMA/ConsensusPDB analysis WITHOUT WARRANTY.

# Yunhan Chu (yunhanch@gmail.com), Guy F. L. Hindley

# (c) 2020-2022 NORMENT, UiO

#-------------------------------------------------------------------------#
if [ $# -lt 3 ]; then
  echo "Usage:     sh fdr_cpdb_pathway_table.sh fdr_fuma_gene_table cpdb_ora_file outfile"
  echo "Arguments: fdr_fuma_gene_table - TRAIT1_vs_TRAIT2_genes.txt file generated by script fdr_fuma_gene_table.sh"
  echo "           cpdb_ora_file - file that contains cpdb gene-set info"
  echo "           outfile - output file"
  echo "Example:   sh fdr_cpdb_pathway_table.sh MD_vs_CRP_genes.txt ORA_MD_CRP.txt MD_vs_CRP_path.txt"
  exit 0
fi
#-------------------------------------------------------------------------#

fdr_fuma_gene_table=$1
cpdb_ora_file=$2
outfile=$3

echo 'genes_input_overlap	credible' > $outfile
awk '$NF=="Yes" {print $1}' $fdr_fuma_gene_table | sort | uniq | sort > $fdr_fuma_gene_table.tmp
tail -n +2 $cpdb_ora_file | cut -f6 | while read id; do
    echo $id | sed 's/; /\n/g' | sort | uniq | sort > $outfile.tmp
    if [ `join $fdr_fuma_gene_table.tmp $outfile.tmp | wc -l` -gt 0 ]; then
        echo $id"	Yes" >> $outfile
    else
        echo $id"	No" >> $outfile
    fi
done
cut -f1-4 $cpdb_ora_file > $cpdb_ora_file.tmp
paste $cpdb_ora_file.tmp $outfile > $outfile.tmp
head -n1 $outfile.tmp > $outfile
sort -t'	' -k4,4 -k3,3 $outfile.tmp | grep 'Yes$' >> $outfile
sort -t'	' -k4,4 -k3,3 $outfile.tmp | grep 'No$' >> $outfile
awk -F '\t' '{print $4,$3,$1,$2,$5,$6}' OFS='\t' $outfile | sed 's/&gamma;/gamma/g' > $outfile.tmp
mv $outfile.tmp $outfile

rm -f $fdr_fuma_gene_table.tmp $cpdb_ora_file.tmp
