#!/bin/bash
#--------------------------- Description ---------------------------------#

# This script generates data for supplementary loci table (cFDR+FUMA+SUMSTAT)
# from cFDR/FUMA analysis, but WITHOUT ANY WARRANTY.

# Yunhan Chu (yunhanch@gmail.com)

# (c) 2020-2022 NORMENT, UiO

#-------------------------------------------------------------------------#
if [ $# -lt 3 ]; then
  echo "Usage:     sh fdr_fuma_loci_table.sh cfdr_clump_loci_file fdr_fuma_snp_table outfolder"
  echo "Arguments: cfdr_clump_loci_file - file that contains cfdr clumping loci info"
  echo "           fdr_fuma_snp_table - file generated by script fdr_fuma_snp_table.sh"
  echo "           outfolder - output folder"
  echo "Example:   sh fdr_fuma_loci_table.sh PGC_BIP_2016_vs_UKB_MOOD_2019_conjfdr/conj.result.clump.loci.csv snp2gene/BIP_vs_MOOD_snps_conj.txt snp2gene"
  exit 0
fi
#-------------------------------------------------------------------------#

cfdr_clump_loci_file=$1
fdr_fuma_snp_table=$2
outfolder=$3

tag1=`basename $fdr_fuma_snp_table | cut -d'_' -f1`
tag2=`basename $fdr_fuma_snp_table | cut -d'_' -f3`

echo "locusnum	CHR	LEAD_SNP	LEAD_BP	MinBP	MinBP	cFDR	non_effect_allele	effect_allele	nearestGene	dist	func	CADD	RDB	minChrState	commonChrState	${tag1}_PVAL	${tag1}_Z	${tag1}_BETA	${tag2}_PVAL	${tag2}_Z	${tag2}_BETA	Concordant_Effect" > $outfolder/${tag1}_vs_${tag2}_loci.txt

sort -s -k3,3 $cfdr_clump_loci_file > $cfdr_clump_loci_file.sorted
sort -s -k1,1 $fdr_fuma_snp_table > $fdr_fuma_snp_table.sorted

join -1 3 -2 1 -a 1 $cfdr_clump_loci_file.sorted $fdr_fuma_snp_table.sorted | grep -v FDR | awk '{print $2,$3,$1,$4,$5,$6,$7,$10,$11,$15,$16,$17,$18,$19,$20,$21,$25,$26,$27,$28,$29,$30,$31}' OFS='\t' | sort -n -k2,2 -k4,4 >> $outfolder/${tag1}_vs_${tag2}_loci.txt

rm -f $cfdr_clump_loci_file.sorted $fdr_fuma_snp_table.sorted
